@extends('site/layouts/siteLayout')

@section('header')
	<meta name="csrf-token" content="{{ csrf_token() }}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

@endsection

@section('content')

<div class="shipping-steps">

	<div class="shipping-steps-dash">
		<div style="margin-right: 25px"></div>
		<div></div>
		<div></div>
		<div></div>
	</div>

	<div class="bullet green tick">
		<span>ورود به دیجی کالا</span>
	</div>

	<div class="shipping-line green-line"></div>


	<div class="bullet green">
		<span>بررسی سفارش</span>
	</div>

	<div class="shipping-line gray-line"></div>

	<div class="bullet grey">
		<span>اطلاعات ارسال</span>
	</div>

	<div class="shipping-line gray-line"></div>

	<div class="bullet grey">
		<span>اطلاعات پرداخت</span>
	</div>

	<div class="shipping-steps-dash-gray">
		<div style="margin-right: 10px"></div>
		<div></div>
		<div></div>
		<div></div>
	</div>
	
</div>

<div style="position: absolute;">
	<br/>
	<br/>
</div>
	


 <form action="{{ action('ShippingController@store') }}" method="POST">
		{{ csrf_field() }}


<div class="shipping-address">

	<div class="add-address">
		<span>آدرس: </span>

		<a href="#" class="btn btn-primary" onclick="add_address()" data-target="#myAddress">
			<i class="fa fa-plus"></i> 
            <span style="font-size: 16px">افزودن آدرس </span>
        </a>
	</div>

	<div>

		<input type="hidden" value="{{ $user_address[0]->id }}" id="selected_shipping_addr" name="selected_shipping_addr">

		@foreach($user_address as $key=>$value)
		<div style="width: 95%; margin: 10px auto">

			<!-- table generated by: https://tabletag.net/ -->

			<table class="table table-bordered">
				<tbody>
					<tr>
						<td rowspan="3" class="active-address" onclick="active_address('{{$key}}', '{{$value->id}}')">

							@if($key==0)
								<span class="fa fa-circle" id="active_address_{{$key}}" style="color:#828181"></span>

							@else
								<span class="fa fa-circle" id="active_address_{{$key}}"></span>
							@endif

							
						</td>
						<td colspan="3"> {{ $value->username }} </td>

						<td rowspan="3" class="users-address-operations">

							<div class="edit" onclick="edit_addr('{{$key}}', '{{$value}}')">
								<span class="fa fa-edit" id="edit_{{$key}}"></span>
							</div>

							<div class="remove" onclick="remove_shipping_address()">
								<span class="fa fa-remove"></span>

								<form action="{{ action('ShippingController@destroyAddress', ['id' => $value->id]) }}" id="url_delete_shipping">
	                    </form>

							</div>

						</td>

					</tr>
					<tr>
						<td>
							<span>استان: </span>
							<span> {{ $value['state']->name }} </span>
						</td>

						<td rowspan="2">
							<div>
								<span> آدرس:  </span>
								<span> {{ $value->address }} </span>
							</div>
							<div>
								<span> کد پستی: </span>
								<span> {{ $value->postalCode }} </span>
							</div>
						</td>

						<td style="width:30%">
							<span>شماره موبایل:</span>
							<span>{{ $value->mobile }}</span>
						</td>

					</tr>
					<tr>

						<td>
							<span>شهر: </span>
							<span> {{ $value['city']->name }} </span>
						</td>

						<td>
							<span>تلفن ثابت:</span>
							<span> {{ $value->telephone }}-{{ $value->city_code }} </span>
						</td>

					</tr>
				</tbody>
			</table>

		</div>
		@endforeach
	</div>

</div>

<div class="shipping_type">

	<div style="padding: 20px 20px 0px 0px">
		<span>
			انتخاب شیوه ارسال:
		</span>
	</div>

	<input type="hidden" value="1" id="selected_shipping_type" name="selected_shipping_type">

	<div class="width_range">
		<table class="table table-bordered" style="width: 100%">
			<tbody>

				<tr>
					<td class="active_shipping_type" onclick="active_shipping_type('1')">
						<span class="fa fa-circle" id="shipping_type_1" style="color: #828181"></span>
					</td>

					<td class="shipping_type_img">
						<img src="{{ url('images/post_48_icon.png') }}">
					</td>

					<td style="padding-top: 20px;">
						<p>تحويل اکسپرس ديجي‌کالا</p>
						<p>
							زمان تحويل: 1 روز کاري درصورت ثبت سفارش تا ساعت 12 (به‌جز جشنواره‌هاي فروش و روزهاي تعطيل)
						</p>
					</td>

					<td class="shipping_type_price">
                       <p>هزینه ارسال </p>
                       <p>15,000 تومان</p>
                   </td>

				</tr>

				<tr>
					<td class="active_shipping_type" onclick="active_shipping_type('2')">
						<span class="fa fa-circle" id="shipping_type_2"></span>
					</td>

					<td class="shipping_type_img">
						<img src="{{ url('images/vtn_48_icon.png') }}">
					</td>

					<td class="shipping_type_2_desc">
						<p>باربري (پس کرايه | لوازم خانگي سنگين)</p>
                        <p>ويژه لوازم خانگي سنگين</p>
					</td>

					<td class="shipping_type_price">
                       <p>هزینه ارسال </p>
                       <p>پس کرايه</p>
                   </td>

				</tr>

			</tbody>
		</table>

	</div>
	
</div>


<div class="submit_shipping">
	<div style="padding-top: 10px">
		<div class="row">
			<div class="col-sm-10"></div>

			<div class="col-sm-2">
				<input type="submit" value="ثبت اطلاعات و ادامه خرید" class="btn btn-success">
			</div>

		</div>
	</div>
</div>

</form>





<div class="container">

  <!-- Modal -->
  <div class="modal fade" id="myAddress" role="dialog" style="background-color:transparent !important">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header"  style="direction: ltr">
          <button type="button" class="close" data-dismiss="modal"></button>
          <h5 class="modal-title" >آدرس</h5>
        </div>

        <div class="modal-body">


          	<form action="#" onsubmit="address_submit() ; return false;" method="POST" accept-charset="utf-8" enctype="multipart/form-data" id="address_form" >
					{{ csrf_field() }}

	        	<label>نام و نام خانوادگی</label>
	        	<input type="text" class="form-control" name="username" id="username" value="{{ old('username') }}" />
	        	<span style="color: red;" id="username_error"></span>


	        	<div class="newAddressModal">
	        		<div>
	        			<div> انتخاب استان و شهر:</div>
		        	<select onchange="state_changed()" name="state" id="state_list" class="form-control newAddressInputs">
					 	<option value="">استان</option>

					 	@if(sizeof($states) > 0)
							@foreach($states as $key_state=>$value_state)
								<option value="{{$value_state->id}}">{{$value_state->name}}</option>
							@endforeach
						@else
							nothing in here
						@endif
					</select>
	        		</div>

					<div>
					<select id="cities_list" class="form-control newAddressInputs" name="city">
					 	<option value="">شهر</option>
					</select>
					</div>

					<span style="color: red;" id="state_error"></span>

					<span style="color:red; margin-right:28%;" id="city_error"></span>

	        	</div>

	        	<br/>

				<div class="newAddressInputs">
					<div> تلفن ثابت</div>
	        		<input type="text" class="form-control" name="telephone" id="telephone" value="{{ old('telephone') }}" />
	        		<span style="color: red;" id="telephone_error"></span>
				</div>

	        	<div class="newAddressInputs">
	        		<div> کد شهر </div>
	        		<input type="text" class="form-control" name="city_code" id="city_code" value="{{ old('city_code') }}" />
	        		<span style="color: red;" id="city_code_error"></span>
	        	</div>

				<div class="newAddressInputs">
					<div> شماره موبایل</div>
	        		<input type="text" class="form-control" name="mobile" id="mobile" value="{{ old('mobile') }}" />
	        		<span style="color: red;" id="mobile_error"></span>
				</div>

	        	<div class="newAddressInputs">
	        		<div> کد پستی </div>
	        		<input type="text" class="form-control" name="postalCode" id="postalCode" value="{{ old('postalCode') }}" />
	        		<span style="color: red;" id="postalCode_error"></span>
	        	</div>

	        	<div style="margin: 10px 0px 10px 0px"></div>

	        	<div class="newAddressTextArea">
	        		<div> آدرس </div>
	        		<textarea class="form-control" name="address" id="address" value="{{ old('address') }}" > </textarea>
	        		<span style="color: red;" id="address_error"></span>
	        	</div>

	        	<input type="submit" class="btn btn-success newAddrSubmit" value="ثبت" />
			</form>

    	</div>

      </div>      
    </div>
  </div>
  
</div>

<!-- Editing Modal -->
<div class="container">

  <!-- Modal -->
  <div class="modal fade" id="myAddressEdit" role="dialog" style="background-color:transparent !important">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header"  style="direction: ltr">
          <button type="button" class="close" data-dismiss="modal"></button>
          <h5 class="modal-title" >ویرایش آدرس</h5>
        </div>

        <div class="modal-body">

        	<div class="loading" id="loading"></div>

          	<form action="#" onsubmit="edit_submit() ; return false;" method="POST" accept-charset="utf-8" enctype="multipart/form-data" id="edit_addr_form" >
					{{ csrf_field() }}

        		<input type="hidden" id="addr_id_edit" name="addr_id_edit">

	        	<label>نام و نام خانوادگی</label>
	        	<input type="text" class="form-control" name="username_edit" id="username_edit" value="" />
	        	<span style="color: red;" id="username_edit_error"></span>


	        	<div class="newAddressModal">
	        		<div>
	        			<div> انتخاب استان و شهر:</div>
		        	<select onchange="state_changed_edit()" name="state_edit" id="state_list_edit" class="form-control newAddressInputs">
					 	<option value="">استان</option>

					 	@if(sizeof($states) > 0)
							@foreach($states as $key_state=>$value_state)
								<option value="{{$value_state->id}}">{{$value_state->name}}</option>
							@endforeach
						@else
							nothing in here
						@endif
					</select>
	        		</div>

					<div>
					<select id="cities_list_edit" class="form-control newAddressInputs" name="city_edit">
					 	<option value="">شهر</option>
					</select>
					</div>

					<span style="color: red;" id="state_edit_error"></span>

					<span style="color:red; margin-right:28%;" id="city_edit_error"></span>

	        	</div>

	        	<br/>

				<div class="newAddressInputs">
					<div> تلفن ثابت</div>
	        		<input type="text" class="form-control" name="telephone_edit" id="telephone_edit" value="" />
	        		<span style="color: red;" id="telephone_edit_error"></span>
				</div>

	        	<div class="newAddressInputs">
	        		<div> کد شهر </div>
	        		<input type="text" class="form-control" name="city_code_edit" id="city_code_edit" value="" />
	        		<span style="color: red;" id="city_code_edit_error"></span>
	        	</div>

				<div class="newAddressInputs">
					<div> شماره موبایل</div>
	        		<input type="text" class="form-control" name="mobile_edit" id="mobile_edit" value="" />
	        		<span style="color: red;" id="mobile_edit_error"></span>
				</div>

	        	<div class="newAddressInputs">
	        		<div> کد پستی </div>
	        		<input type="text" class="form-control" name="postalCode_edit" id="postalCode_edit" value="" />
	        		<span style="color: red;" id="postalCode_edit_error"></span>
	        	</div>

	        	<div style="margin: 10px 0px 10px 0px"></div>

	        	<div class="newAddressTextArea">
	        		<div> آدرس </div>
	        		<textarea class="form-control" name="address_edit" id="address_edit" value="" > </textarea>
	        		<span style="color: red;" id="address_edit_error"></span>
	        	</div>

	        	<input type="hidden" name="_method" value="PATCH">

	        	<input type="submit" class="btn btn-primary newAddrSubmit" value="ویرایش" />
			</form>

    	</div>

      </div>      
    </div>
  </div>
  
</div>




@endsection

@section('footer')

<script type="text/javascript">

	add_address = function()
	{
		$('#myAddress').modal('show');
	}

	<?php $url_view_cities = url('shipping/ajax_view_cities'); ?>
	state_changed = function()
	{
		state = document.getElementById("state_list").value;
		
		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

	    		'url': '{{ $url_view_cities }}',
	    		'type': 'post',
	    		'data': 'state='+state,
	    		success:function(data){

	    			data = JSON.parse(data);

	    			var generat_options = "";

	    			for (var i = 0; i < data.length; i++)
	    			{
	    				generat_options += '<option value="'+data[i]["id"]+'">'+
	    							  	  data[i]["name"]+
	    							  	  '</option>';

	    				$("#cities_list").html(generat_options);
	    			}

	    			if(data.length == 0)
	    			{
	    				generat_options = '<option value="">شهر</option>';
	    				$("#cities_list").html(generat_options);
	    			}
	    		}

	    		}
		  );
	}

	<?php $url_storeAddress= url('shipping/storeAddress'); ?>
	address_submit = function()
	{
		var form_data = $("#address_form").serialize();

		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

	    		'url': '{{ $url_storeAddress }}',
	    		'type': 'post',
	    		'data': 'form_data='+form_data,
	    		success:function(data){

	    			if(data == 'ok')
	    			{
	    				alert("ثبت اطلاعات با موفقیت انجام شد.");
	    				var redirectTo = window.location.origin+"/shipping/";
						document.location = redirectTo;
	    			}

	    			else
	    			{
	    				if(data == 'error')
	    					alert("مجددا تلاش کنید");

	    				else
	    				{
	    					clear_errors("");

			    			var data = Object.entries(data);

			    			data.forEach(([key, value]) => {
							  $("#"+key+"_error").html(value);
							});
	    				}
	    			}
	    			
	    		}

	    		}
		  );
	}



	function clear_errors(edit)
	{
		var error_fields = ['username','state','city','telephone','city_code','mobile','postalCode','address'];

		for (var i = 0; i < error_fields.length; i++)
		{
			$("#"+error_fields[i]+edit+"_error").html(" ");
		}
	}

	active_address = function(key, shipping_id)
	{
		document.getElementById('default_shipping_addr').value='';
		document.getElementById('selected_shipping_addr').value=shipping_id;


		for (var i = 0; i < (<?= $user_address; ?>).length; i++)
		{
			document.getElementById('active_address_'+i).style.color="white";
		}
		
		document.getElementById('active_address_'+key).style.color="#828181";
	}

	edit_addr = function(key, value)
	{
		clear_errors("_edit");

		$('#myAddressEdit').modal('show');

		show_loading();

		value = JSON.parse(value);
		document.getElementById("addr_id_edit").value = value["id"];

		var fields = ['username','telephone','city_code','mobile','postalCode','address'];

		for (var i = 0; i < fields.length; i++)
		{
			document.getElementById(fields[i]+"_edit").value= value[fields[i]];
		}

		var state_id = value['state']['id'];

		document.getElementById("state_list_edit").value = state_id;
		

		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

	    		'url': '{{ $url_view_cities }}',
	    		'type': 'post',
	    		'data': 'state='+state_id,
	    		success:function(data){
	    			data = JSON.parse(data);

	    			var generat_options = "";

	    			for (var i = 0; i < data.length; i++)
	    			{
	    				if( value['city']['id'] == data[i]["id"])
	    				{
	    					generat_options += '<option value="'+data[i]["id"]+'" selected >'+
	    							  	  data[i]["name"]+
	    							  	  '</option>';
	    				}
	    				else
	    				{
	    					generat_options += '<option value="'+data[i]["id"]+'">'+
	    							  	  data[i]["name"]+
	    							  	  '</option>';
	    				}

	    				$("#cities_list_edit").html(generat_options);
	    			}

	    			if(data.length == 0)
	    			{
	    				generat_options = '<option value="">شهر</option>';
	    				$("#cities_list_edit").html(generat_options);
	    			}

	    			},
	    		error:function()
	    		{
	    			window.location = '<?= url("login"); ?>';
	    		}

	    		}
		  );		
	}

	state_changed_edit = function()
	{
		state = document.getElementById("state_list_edit").value;
		
		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

	    		'url': '{{ $url_view_cities }}',
	    		'type': 'post',
	    		'data': 'state='+state,
	    		success:function(data){

	    			data = JSON.parse(data);

	    			var generat_options = "";

	    			for (var i = 0; i < data.length; i++)
	    			{
	    				generat_options += '<option value="'+data[i]["id"]+'">'+
	    							  	  data[i]["name"]+
	    							  	  '</option>';

	    				$("#cities_list_edit").html(generat_options);
	    			}

	    			if(data.length == 0)
	    			{
	    				generat_options = '<option value="">شهر</option>';
	    				$("#cities_list_edit").html(generat_options);
	    			}
	    		}

	    		}
		  );
	}

	function show_loading()
	{
		// showing "loader" if ajax takes more than 500 miliseconds (35349470)
	    var ajaxLoadTimeout;

		$(document).ajaxStart(function() {
		    ajaxLoadTimeout = setTimeout(function() { 
		        $("#loading").css("display","block");
		    }, 500);

		}).ajaxSuccess(function() {
		    clearTimeout(ajaxLoadTimeout);
		    $("#loading").css("display","none");
		});
	}

	<?php $url_storeAddress= url('shipping/updateAddress'); ?>
	edit_submit = function()
	{
		var address_id = document.getElementById("addr_id_edit").value;

		url_update = <?php echo json_encode($url_storeAddress); ?>+"/"+address_id;

		data = $("#edit_addr_form").serialize();



		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

	    		'url': url_update,
	    		'type': 'patch',
	    		'data': 'data='+data,
	    		success:function(data){
	    				if(data == 'ok')
	    				{
							alert("ویرایش اطلاعات با موفقیت انجام شد.");
		    				var redirectTo = window.location.origin+"/shipping/";
							document.location = redirectTo;
	    				}
	    				else
	    				{
	    					if(data == 'error')
	    					{
	    						alert("خطا رخ داده است. مجدد تلاش کنید.");
	    					}

	    					else
		    				{
				    			var data = Object.entries(data);

				    			clear_errors("_edit");

				    			data.forEach(([key, value]) => {
								  $("#"+key+"_error").html(value);
								});
		    				}
	    				}
	    			}
	    		}
		  );


	}

	<?php $url_destroyAddress= url('shipping'); ?>
	remove_shipping_address = function()
	{
		var url_delete_shipping = document.getElementById('url_delete_shipping').action;
		var redirectTo          = window.location.origin+"/shipping/";

		$.ajaxSetup(
		    			{
		    				'headers':
		    				{
		    					'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')
		    				}
		    			}
					);
		
		$.ajax(
	    		{

		    		'url': url_delete_shipping,
		    		'type': 'delete',
		    		//'data': 'id='+id,
		    		success:function(data)
		    		{
		    			if(data == 'ok')
		    			{
		    				alert("حذف آدرس با موفقیت انجام شد.");
							document.location = redirectTo;
		    			}
		    			if(data == 'ko')
		    			{
		    				alert("حذف آدرس با خطا مواجه شد.");
		    			}
		    		},
		    		error:function()
		    		{
						document.location = redirectTo;	
		    		}
	    		}
		  );
	}

	active_shipping_type = function(id)
	{
		document.getElementById('selected_shipping_type').value=id;

		document.getElementById('shipping_type_1').style.color="white";
		document.getElementById('shipping_type_2').style.color="white";
		
		document.getElementById('shipping_type_'+id).style.color="#828181";
	}

</script>

@endsection